### PR TITLE
fix: enum values should be of type enum-value

### LINKED ISSUE #231: Enum value type should be "enum-value" not "string"
So, although enums are strings in JS, the type is not representative of the data type... it should be "enum-value".

### PR DESCRIPTION
**Pull request by marcoscaceres**
* closes #231 

- [ ]  update docs once this is merged.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Was not sure if this is a breaking change or not

**Comment by marcoscaceres** [comment]
it might be a breaking change... given:
https://github.com/w3c/respec/pull/1850/files#diff-e45f88cac27757d7ac69556862e6226bR515

And:
https://github.com/w3c/respec/pull/1850/files#diff-e45f88cac27757d7ac69556862e6226bR758

@saschanaz wdyt?

**Comment by marcoscaceres** [comment]
Note to self: update docs once this is merged.

**Comment by saschanaz** [comment]
I agree, this also changes the documented API, so a major change.

**Comment by marcoscaceres** [comment]
updating the docs

**Pull request merged**
