### PR TITLE
Allow "constructor" as an argument name

### PR DESCRIPTION
**Pull request by Ms2ger**
This patch includes:
- [ ] A relevant test
- [ ] A relevant documentation update

### CODE REVIEW

**Comment by saschanaz** [comment]
This needs a test, and I just added one. Thanks!

**Comment by foolip** [comment]
Is a new webidl2.js release in the pipeline? We need this to roll webidl2.js in web-platform-tests, and I just noticed https://github.com/foolip/mdn-bcd-collector/pull/132 is failing because of the "constructor" argument as well.

**Comment by saschanaz** [comment]
@foolip Just published a new release v23.8.0 🎉

**Comment by foolip** [comment]
Thanks @saschanaz!

**Pull request merged**
