### PR TITLE
refactor: rename consumeType to consumeKind

### PR DESCRIPTION
**Pull request by saschanaz**
"type" has a special meaning in Web IDL (idl type), so probably better to use "kind" rather than overloading the word.

This patch closes #__ and includes:
- [x] A relevant test
- [x] A relevant documentation update

### CODE REVIEW

**Review by marcoscaceres — APPROVED** [review]
"consume kind" make good sense.

**Comment by saschanaz** [comment]
@marcoscaceres I'm now a little hesitant here, which would you prefer between consumeKind or consumeByKind? Somehow the former sounds like a property name 🤔

**Comment by marcoscaceres** [comment]
I don't mind, tbh.. "consume" is a verb, so it still works well for the method name... but consumeByKind makes it even more clear. Either is fine by me.

**Comment by saschanaz** [comment]
Cool, I'll merge this and see how people feels when we expose tokenisers.

**Pull request merged**
