### PR TITLE
DO NOT MERGE YET: Drop support for implements statement

### LINKED ISSUE #98: Remove implements statement support
I think "implements" has been dropped from the IDL spec... probably when "mixin" happened... 

Affected specs: https://github.com/heycam/webidl/issues/472

### PR DESCRIPTION
**Pull request by saschanaz**
Fixes #98, but merge after specs remove the syntax.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@SaschaNaz, when you have minute, could you please rebase?

**Comment by marcoscaceres** [comment]
@saschanaz, you should probably rebase this before it gets worst.

**Comment by saschanaz** [comment]
Travis says "This is not an active repository", any idea what happened there? @marcoscaceres

**Comment by marcoscaceres** [comment]
Sent an empty commit in an attempt to restart Travis. This branch wasn't showing up :/

**Comment by marcoscaceres** [comment]
Starting to get a little of bit of bit rot here. @saschanaz, mind updating it?

**Comment by saschanaz** [comment]
Do we still have a blocker here?

**Comment by marcoscaceres** [comment]
blockers: 
https://github.com/w3c/web-platform-tests/issues/8053
https://github.com/w3c/webappsec-credential-management/issues/111

**Comment by marcoscaceres** [comment]
It might accelerate things if we send a PR to fix w3c/webappsec-credential-management#111. @saschanaz, I've not looked at the appropriate use of `mixin`, so would you be willing to send them one?

**Comment by marcoscaceres** [comment]
Once the Credential Management spec is fixed, I think it automatically fixes w3c/web-platform-tests#8053 - because all the updated specs will be testing what was required there.  

I've asked @tobie to clarify if my assumption holds.

**Comment by marcoscaceres** [comment]
I think we should consider merging this. All the specs have been updated. The WPT issues can be fixed incrementally (along with any now outdated WebIDL in WPT).

**Comment by saschanaz** [comment]
I have no objection. I know some specs haven't updated their snapshots yet, but that's okay for me.

**Comment by marcoscaceres** [comment]
#yolo 😅

**Pull request merged**
