### PR TITLE
fix: enable extattr argument validation

### PR DESCRIPTION
**Pull request by saschanaz**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
We should release this nowish too, so all ` = {}` can get flagged at once. Let me know if you want me to do it.

**Comment by saschanaz** [comment]
Feel free to release this 🎉

**Comment by marcoscaceres** [comment]
ok, webidl2@23.2.2 🎉 updating ReSpec...

**Comment by saschanaz** [comment]
@marcoscaceres Don't forget `git push --follow-tags` 😁

**Comment by marcoscaceres** [comment]
I'm on a different computer now... but I did do, `git push tags`, or is that different?

**Comment by saschanaz** [comment]
`git push --tags` only pushes tags, so I can't see the relevant commits on `gh-pages` branch. But no worry, I can push them!

**Comment by saschanaz** [comment]
(Just pushed the 3 commits)

**Pull request merged**
