### PR TITLE
Fix JS error on productions/default.js bracket errors

### PR DESCRIPTION
**Pull request by kainino0x**

### CODE REVIEW

**Comment by saschanaz** [comment]
Really need attaching some static analyzer.

**Comment by saschanaz** [comment]
@kainino0x Could you add a test for this? You can add a short relevant IDL code in `test/syntax/idl/` and run `npx webpack && npm run acquire`.

**Comment by saschanaz** [comment]
Not sure why Travis never runs. I confirmed this locally passes the test, so I'm merging this.

**Comment by kainino0x** [comment]
Thanks so much for adding the test. I have been in all day standardization meetings this week so I haven't been able to look back at it.

**Pull request merged**
