### PR TITLE
Class, extends (opt-in flags)

### PR DESCRIPTION
**Pull request by motiz88**
Even I'm not sure about this one, but I can't parse http://dom.spec.whatwg.org/#elements otherwise.
Anyway, this reuses the infrastructure from #32 for opting-in to nonstandard syntax.

### CODE REVIEW

**Comment by jyasskin** [comment]
@annevk @heycam can you work on getting the syntax from https://dom.spec.whatwg.org/#element-collections into the WebIDL draft?

**Comment by annevk** [comment]
The DOM specification points to two bugs meant to do just that.

**Comment by marcoscaceres** [comment]
I thinks this is no longer valid, right @motiz88?

**Comment by marcoscaceres** [comment]
(closing, but let me know if I should reopen)

**Pull request closed without merging**
